### ISSUE TITLE
OP1.0.1 - Receive CR approval for system access

### ISSUE THREAD

**Issue by mbalestrino** [mkaczynski11/playground#5]
### Description: 
As any user, I want to share my contact info, so I can join the platform.

### Wireframe: 
Intake Form

### Acceptance Criteria: 
N/A - offline process

### Associated Objects: 
None

### L1 Process ID: 
ZM-010-020

### L2 Process ID: 
N/A

### Remarks (if any): 

"

**Comment by mkaczynski11** [comment]
![image](https://user-images.githubusercontent.com/22941253/39612369-a9bc429c-4f13-11e8-9a87-42aae40253ca.png)

**Comment by mkaczynski11** [comment]
![image](https://user-images.githubusercontent.com/22941253/39612371-b7368f18-4f13-11e8-8abe-319113da2173.png)

**Comment by mkaczynski11** [comment]
![image](https://user-images.githubusercontent.com/22941253/39612382-ca01a0f6-4f13-11e8-81a5-e8eaaf0cd1a8.png)

**Comment by mkaczynski11** [comment]
![image](https://user-images.githubusercontent.com/22941253/39612549-59812714-4f15-11e8-9047-2f2a05941e84.png)

**Comment by mbalestrino** [comment]
@mkaczynski11 Testing fun? Or do I need to take action?
